language: python
python: '2.7'

before_install:
  - sudo apt-get update -qq
  - mkdir ~/.azure
  - touch ~/.azure/credentials
  - printf "[default]\nsubscription_id=${subscriptionId}\nclient_id=${clientId}\nsecret=${secret}\ntenant=${tenant}" > ~/.azure/credentials

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible[azure]; else pip install ansible[azure]; fi
  - "{ echo '[defaults]'; echo 'roles_path = ../'; echo 'lookup_plugins = ./tests/integration/targets/azure_rm_keyvaultkey/lookup_plugins'; } >> ansible.cfg"
  - ansible --version
  - pip install -I -r ./files/requirements-azure.txt
  - pip install xmltodict
  - pip freeze
  - git remote set-branches --add origin master
  - git fetch

script:
  - ansible-playbook -vvv tests/integration/clear_all.yml
