language: python
python: '2.7'

before_install:
  - sudo apt-get update -qq
  - mkdir ~/.azure
  - touch ~/.azure/credentials
  - printf "[default]\nsubscription_id=${subscriptionId}\nclient_id=${clientId}\nsecret=${secret}\ntenant=${tenant}" > ~/.azure/credentials

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible[azure]; else pip install ansible[azure]; fi
  - pip install -I -r ./files/requirements-azure.txt
  - pip  freeze

script:
  - ansible-playbook -vvv tests/integration/clear_all.yml
